name: git cicd
on:
  push:
    branches:
      - main
      - dev1
env:
  DOCKER_USERNAME: xqcao
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      all_users: ${{steps.helloabc.outputs.ALL_USERS}}
    services:
      svc-01:
        image: nginx
        ports:
          - 80:80
      svc-02:
        image: chapinme/gitflaskapp:16
        ports:
          - 5001:5001
    steps:
      # - name: check container running
      #   run: http://localhost:80
      - name: run curl
        run: curl http://localhost:80
      - name: run curl user svc
        run: curl http://localhost:5001
      - name: get all users
        id: helloabc
        run: 'echo ALL_USERS=$(curl http://localhost:5001/api/users -H "Accept: application/json")  >> $GITHUB_OUTPUT'
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: get user
        run: echo ${{needs.job1.outputs.all_users}}
